import Config


config :logatron, Logatron.Repo,
  username: System.get_env("POSTGRES_USER"),
  password: System.get_env("POSTGRES_PASSWORD"),
  hostname: "postgres",
  database: System.get_env("LOGATRON_DB"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :logatron_edge, Edge.Client,
  uri: "wss://logatron.io/edge_socket/websocket",
  reconnect_after_msec: [200, 500, 1_000, 2_000]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :logatron_web, LogatronWeb.Endpoint,
  url: [host: "logatron.io", port: 443],
  server: true,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, Logatron.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
